// import './globals.css'
import './globalStyle.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ dashboard, auth }) {
  const isLoggedIn = true  
  return (
    <html lang='en'>
      <body className={inter.className}>{isLoggedIn ? dashboard : auth}</body>
    </html>
  )
}

//https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes